name: CI Common - Lint and Build

on:
  workflow_call:
    inputs:
      path:
        description: "Path to the project (e.g., .)"
        required: false
        type: string
        default: "."
      node-version:
        description: "Node.js version"
        required: false
        type: string
        default: "22"

jobs:
  lint-and-build:
    name: Lint, Test & Build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    defaults:
      run:
        working-directory: ${{ inputs.path }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Node with cache
        uses: actions/setup-node@v5
        with:
          node-version: ${{ inputs.node-version }}
          cache: "npm"
          cache-dependency-path: ${{ format('{0}/package-lock.json', inputs.path) }}

      - name: Pin npm to v9
        run: npm i -g npm@9

      - name: Install dependencies
        run: npm ci

      - name: Run Lint
        run: npm run lint

      - name: Check if test script exists
        id: check-test
        run: |
          if npm run | grep -q "test"; then
            echo "has-test=true" >> $GITHUB_OUTPUT
          else
            echo "has-test=false" >> $GITHUB_OUTPUT
          fi

      - name: Run Tests with Coverage
        if: steps.check-test.outputs.has-test == 'true'
        run: npm test -- --coverage --passWithNoTests
        env:
          CI: true

      - name: Upload Coverage Reports
        if: steps.check-test.outputs.has-test == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: ${{ inputs.path }}/coverage
          retention-days: 30

      - name: Build
        run: npm run build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: ${{ inputs.path }}/dist
          retention-days: 7
